name: cativou
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  shared_preferences: ^2.0.11
  image_picker: ^0.8.4+4
  webview_flutter: ^3.0.0
  flutter_launcher_icons: ^0.9.2
  path: ^1.8.0
  mask_text_input_formatter: ^2.0.0
  image_cropper: ^1.4.1
  google_sign_in: ^5.2.3
  flutter_signin_button: ^2.0.0
  provider: ^6.0.2
  flutter_facebook_auth: ^4.0.1
  flutter_native_splash: ^2.0.4
  flutter_barcode_scanner: ^2.0.0
  rflutter_alert: ^2.0.4

flutter_native_splash:
  background_image: images/fundoSplash3.png

flutter_icons:
  ios: true
  android: true
  image_path_ios: "images/iconIos.png"
  image_path_android: "images/iconAndroid2.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/fundoCativou.jpg
    - images/backIco.png
    - images/homeIco.png
    - images/shieldIco.png
    - images/cativouLogo.png
    - images/cativouLogoWhite.png
    - images/bottomNav/icoCalendar.png
    - images/bottomNav/icoCadeira.png
    - images/bottomNav/icoPerfil.png
    - images/bottomNav/icoTicket.png
    - images/bottomNav/icoCadeiraAlt.png
    - images/bottomNav/icoCalendarAlt.png
    - images/bottomNav/icoPerfilAlt.png
    - images/bottomNav/icoTicketAlt.png
    - images/bottomNav/icoEstadioAlt.png
    - images/bottomNav/icoEstadio.png
    - images/cativouInitialLogo.png
    - images/tour/tour01.png
    - images/tour/tour02.png
    - images/tour/tour03.png
    - images/tour/tour04.png
    - images/tour/tour05.png
    - images/tour/tour06.png
    - images/tour/rightIco.png
    - images/tour/leftIco.png
    - images/tour/closeIco.png
    - images/tour/header01.png
    - images/tour/header02.png
    - images/tour/futebolEvento.png
    - images/tour/barraInferior.png
    - images/tour/barraInferior01.png
    - images/tour/barraInferior02.png
    - images/tour/barraInferior03.png
    - images/tour/barraInferior04.png
    - images/qr.png
    - images/setor/setor_a.png
    - images/setor/setor_b.png
    - images/setor/setor_c.png
    - images/setor/setor_d.png
    - images/setor/setor_e.png
    - images/setor/silhuetaEstadio.png
    - images/maracanaChoice.png
    - images/arenaChoice.png
    - images/arena_pb.png
    - images/historicoFinanIco.png
    - images/ico_camera_perfil.png
    - images/ico_foto_perfil.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
